// Builds the `default` building-part theme: a texture atlas, one .glb per part slot
// (geometry + atlas UVs, no embedded texture), and a manifest describing the kit.
// Run: npm run build:parts
//
// Parts are authored to a shared grid — bay width B, floor height H — so they
// interlock. Posts/windows/doors are RIGID; panels are FLEX (X-scaled to fill a bay).
// Roof SHAPES are generated by the client (textured via the atlas), so only repeatable
// parts are exported here.
import * as THREE from 'three'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { encodePNG } from './lib/png.mjs'
import { buildAtlas } from './lib/atlas.mjs'
import { box, merge } from './lib/geom.mjs'

// GLTFExporter (binary) uses FileReader on a Blob; shim for headless Node.
if (typeof globalThis.FileReader === 'undefined') {
  globalThis.FileReader = class {
    readAsArrayBuffer(b) { b.arrayBuffer().then((ab) => { this.result = ab; this.onloadend?.() }) }
    readAsDataURL(b) { b.arrayBuffer().then((ab) => { this.result = 'data:application/octet-stream;base64,' + Buffer.from(ab).toString('base64'); this.onloadend?.() }) }
  }
}
const { GLTFExporter } = await import('three/examples/jsm/exporters/GLTFExporter.js')

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'resources', 'buildingparts', 'default')
mkdirSync(OUT, { recursive: true })

// ── Canonical grid ──────────────────────────────────────────────────────────────
const B = 1.0      // bay width
const H = 1.4      // floor height
const POST = 0.12  // post thickness
const WALL = 0.10  // wall panel thickness
const PROUD = 0.02 // how far features stand off the wall

// ── Atlas ────────────────────────────────────────────────────────────────────────
const atlas = buildAtlas(1)
writeFileSync(join(OUT, 'atlas.png'), encodePNG(atlas.size.w, atlas.size.h, atlas.pixels))
const R = atlas.regions
console.log(`atlas: ${atlas.size.w}×${atlas.size.h}, materials: ${Object.keys(R).join(', ')}`)

// ── Part builders (each returns a merged BufferGeometry, base at y=0, wall face +Z) ──
function post() { return box(POST, H, POST, R.woodtrim, 0, H / 2, 0) }
function panel(region) { return box(B, H, WALL, region, 0, H / 2, 0) }

// Parametric window: cols×rows panes, optional shutters ('open' beside / 'closed' over).
function makeWindow({ w = 0.55, h = 0.85, sill = 0.42, cols = 2, rows = 2, shutters = 'none' }) {
  const z = WALL / 2 + PROUD, fr = 0.05, cy = sill + h / 2, g = []
  g.push(box(w, h, 0.02, R.glass, 0, cy, z))
  g.push(box(w + 2 * fr, fr, 0.06, R.woodtrim, 0, sill + h + fr / 2, z))                  // lintel
  // Sill: thicker, longer, and protruding ~2× from the wall.
  g.push(box(w + 4 * fr, 0.09, 0.18, R.woodtrim, 0, sill - 0.045, WALL / 2 + 0.07))
  g.push(box(fr, h + 2 * fr, 0.06, R.woodtrim, -(w / 2 + fr / 2), cy, z))
  g.push(box(fr, h + 2 * fr, 0.06, R.woodtrim, (w / 2 + fr / 2), cy, z))
  for (let c = 1; c < cols; c++) g.push(box(0.03, h, 0.05, R.woodtrim, -w / 2 + c * w / cols, cy, z))
  for (let r = 1; r < rows; r++) g.push(box(w, 0.03, 0.05, R.woodtrim, 0, sill + r * h / rows, z))
  if (shutters === 'closed') {
    g.push(box(w / 2 - 0.01, h, 0.04, R.doorwood, -w / 4, cy, z + 0.03))
    g.push(box(w / 2 - 0.01, h, 0.04, R.doorwood, w / 4, cy, z + 0.03))
  } else if (shutters === 'open') {
    g.push(box(w / 2, h, 0.04, R.doorwood, -(w / 2 + w / 4 + fr), cy, z))
    g.push(box(w / 2, h, 0.04, R.doorwood, (w / 2 + w / 4 + fr), cy, z))
  }
  return merge(g)
}

function door() {
  const dw = 0.6, dh = 1.1, fr = 0.07, z = WALL / 2 + PROUD
  return merge([
    box(dw, dh, 0.05, R.doorwood, 0, dh / 2, z),                           // dark, vertical-grain slab
    box(dw + 2 * fr, fr, 0.07, R.woodtrim, 0, dh + fr / 2, z),             // lintel
    box(fr, dh + fr, 0.07, R.woodtrim, -(dw / 2 + fr / 2), (dh + fr) / 2, z),
    box(fr, dh + fr, 0.07, R.woodtrim, (dw / 2 + fr / 2), (dh + fr) / 2, z),
  ])
}

function eave() { return box(B, 0.08, 0.25, R.woodtrim, 0, 0.04, 0.05) }    // FLAT fascia trim, length=B
function eaveAngled() {                                                     // ANGLED soffit (sloped), length=B
  const g = box(B, 0.07, 0.36, R.woodtrim, 0, 0, 0)
  g.rotateX(-0.5); g.translate(0, 0.05, 0.07)
  return g
}
function beam() { return box(B, 0.11, 0.16, R.woodtrim, 0, 0.055, WALL / 2 + 0.01) }  // floor-line beam, flex
// Diagonal knee braces for a LEFT corner (post at x=-B/2), mirrored (scale.x=-1) for
// the right. `brace` is a single long diagonal; `brace-double` adds a second strut.
function braceGeo(len, ang, tx, ty) {
  const g = box(len, 0.09, 0.1, R.woodtrim, 0, 0, WALL / 2 + 0.005)
  g.rotateZ(ang); g.translate(tx, ty, 0)
  return g
}
function brace() { return braceGeo(1.07, 1.14, -B / 2 + 0.275, H * 0.55) }
function braceDouble() { return merge([braceGeo(1.07, 1.14, -B / 2 + 0.275, H * 0.55), braceGeo(0.62, 1.0, -B / 2 + 0.13, H * 0.74)]) }

const PARTS = {
  post:             { geo: post(),               kind: 'post',    flex: false },
  beam:             { geo: beam(),               kind: 'beam',    flex: true },
  'panel-stone':    { geo: panel(R.stone),       kind: 'panel',   flex: true },
  'panel-wood':     { geo: panel(R.wood),        kind: 'panel',   flex: true },
  'panel-plaster':  { geo: panel(R.plaster),     kind: 'panel',   flex: true },
  window:           { geo: makeWindow({ cols: 2, rows: 2 }),                   kind: 'feature', flex: false },
  'window-short':   { geo: makeWindow({ cols: 3, rows: 1, w: 0.7, h: 0.5, sill: 0.62 }), kind: 'feature', flex: false },
  'window-single':  { geo: makeWindow({ cols: 1, rows: 1, w: 0.42, h: 0.7, sill: 0.5 }), kind: 'feature', flex: false },
  'window-shutter': { geo: makeWindow({ cols: 2, rows: 2, shutters: 'open' }), kind: 'feature', flex: false },
  'window-closed':  { geo: makeWindow({ cols: 2, rows: 2, shutters: 'closed' }), kind: 'feature', flex: false },
  door:             { geo: door(),               kind: 'feature', flex: false },
  brace:            { geo: brace(),              kind: 'brace',   flex: false },
  'brace-double':   { geo: braceDouble(),        kind: 'brace',   flex: false },
  eave:             { geo: eave(),               kind: 'trim',    flex: true },
  'eave-angled':    { geo: eaveAngled(),         kind: 'trim',    flex: true },
}

// ── Export each part as a .glb (geometry only; client applies the atlas) ───────────
const exporter = new GLTFExporter()
function exportGLB(scene) {
  return new Promise((res, rej) => exporter.parse(scene, (r) => res(Buffer.from(r)), rej, { binary: true }))
}

// Parts the artist hand-corrected in a GLB editor: keep the existing file (don't
// overwrite with the procedural placeholder), but still list them in the manifest. They
// are regenerated only if missing (e.g. a fresh checkout).
const PRESERVE = new Set(['brace', 'brace-double'])

const manifest = { grid: { bayWidth: B, floorHeight: H, postThickness: POST, wallThickness: WALL }, atlas: 'atlas.png', atlasRegions: R, parts: {} }
for (const [name, def] of Object.entries(PARTS)) {
  const file = join(OUT, `${name}.glb`)
  const keep = PRESERVE.has(name) && existsSync(file)
  if (!keep) {
    const scene = new THREE.Scene()
    scene.add(new THREE.Mesh(def.geo, new THREE.MeshStandardMaterial({ color: 0xffffff, roughness: 0.8 })))
    writeFileSync(file, await exportGLB(scene))
  }
  def.geo.computeBoundingBox()
  const bb = def.geo.boundingBox
  manifest.parts[name] = {
    kind: def.kind, flex: def.flex,
    size: { x: +(bb.max.x - bb.min.x).toFixed(3), y: +(bb.max.y - bb.min.y).toFixed(3), z: +(bb.max.z - bb.min.z).toFixed(3) },
  }
  console.log(`  ${name}.glb (${def.kind}${def.flex ? ', flex' : ''})${keep ? ' [preserved]' : ''}`)
}
writeFileSync(join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2))
console.log(`Wrote ${Object.keys(PARTS).length} parts + atlas + manifest to ${OUT}`)
