import FeatureManager from './FeatureManager.js'
import { pointInPolygon, posHash } from './renderUtils.js'
import { MODEL_BY_NAME, MODEL_SCALE } from '../../../shared/buildingCatalogue.js'
import PartLibrary from '../buildings/PartLibrary.js'
import { assemble } from '../buildings/ParametricBuilding.js'

const PARA_SCALE = MODEL_SCALE / 2.3          // parametric model-unit → world-unit scale
const PARA_LIB_PATH = '/resources/buildingparts/default'

// ── District → model weighting matrix ────────────────────────────────────────
// Per district type, the building models allowed and their relative weight.
// Absent / 0 = never; higher = more likely when several models fit a plot equally
// well. District keys: Residential-Slums/Middle/Noble, Market, Leadership,
// Religious, Magical, Military, Industry, Entertainment, default. Edit freely.


// 2,3,4 = brick town houses variants
// 5+6 = half stone plaster variants

// 7+10+11 = barn/farm stone  

// 8+9 = wood roof red 
// 12 = wood shingle 
// 13 = stone multi story 
// 14+17 = log hut 
// 15 = slate roof plaster multi story 
// 16 + 18+19 = Bankers German house wood and stone
// m1 + t4  = market tower 
// m2 = lords house
// t1 = barn/farm stone tower
// t2 = lords tower
// t3 = military tower
// t5 = dilapidated 4 story building

// alchemists
// church
// forge
// hall
// watchmaker
// waterwheel

// Landmark buildings per district now live in shared/buildingCatalogue.js
// (DISTRICT_MODEL_SQUARE) — the SERVER places them before plots (ADR-0005). The
// client only renders the recorded landmarkBuildings.
// ── Per-district parametric building style profiles ──────────────────────────
// Controls probability distributions for floors, wall materials, roof type, and
// eave overhang for Residential plots generated by _buildSpec.
//   woodChance     – probability nonstone material is wood (vs plaster)
//   stoneChance    – probability ground floor uses stone
//   graniteChance  – probability stone variant is granite (vs regular stone)
//   mixedChance    – probability upper floors use nonstone when ground is stone (jetty-eligible)
//   roof           – relative weights, normalised internally; order defines tiebreak
//   overhangMin/Max – world-unit eave overhang range passed to ParametricBuilding
const DISTRICT_BUILDING_STYLES = {
  'Residential-Slums': {
    floors:       { 1: 1.00 },
    woodChance:   0.75,
    stoneChance:  0.05,
    graniteChance: 0.00,
    mixedChance:  0.00,
    roof:         { thatch: 0.70, reed: 0.25, slate: 0.05 },
    overhangMin:  0.06, overhangMax: 0.20,
  },
  'Residential-Middle': {
    floors:       { 1: 0.45, 2: 0.55 },
    woodChance:   0.50,
    stoneChance:  0.35,
    graniteChance: 0.15,
    mixedChance:  0.55,
    roof:         { thatch: 0.45, slate: 0.35, reed: 0.20 },
    overhangMin:  0.12, overhangMax: 0.42,
  },
  'Residential-Noble': {
    floors:       { 2: 0.65, 3: 0.35 },
    woodChance:   0.20,
    stoneChance:  0.80,
    graniteChance: 0.25,
    mixedChance:  0.85,
    roof:         { slate: 0.72, reed: 0.18, thatch: 0.10 },
    overhangMin:  0.22, overhangMax: 0.48,
  },
}
const DEFAULT_BUILDING_STYLE = {
  floors:       { 1: 0.50, 2: 0.50 },
  woodChance:   0.50,
  stoneChance:  0.32,
  graniteChance: 0.18,
  mixedChance:  0.50,
  roof:         { slate: 0.40, thatch: 0.32, reed: 0.28 },
  overhangMin:  0.14, overhangMax: 0.48,
}

const DISTRICT_MODEL_WEIGHTS = {
  'Residential-Slums':  { h7: 3, h10: 2, h11: 2, h8: 2, h9: 1, h14:3, h17:3 ,t5:1 ,t1: 1},
  'Residential-Middle': { h8: 3, h9: 3,t5:1, t2:1, h2:2,h3:1,h4:1,h5:2,h6:2,h13:2},
  'Residential-Noble':  { h8: 1, h9: 1, t2:1, h3:1,h4:1,h5:1,h6:1,h13:2,m2:2,h16:2,h18:2,h19:2},
  'Market':             { m1: 3, m2: 1, h8: 1, h9: 1,t5:1, t2:1, h2:2,h3:1,h4:2,h5:2,h6:2,h13:2,h16:3,h18:3,h19:3,watchmaker:2 },
  'Leadership':         { m2: 3, h8: 1, h9: 1, t2:1, h3:1,h4:1,h5:1,h6:1,h13:2,h16:2,h18:2,h19:2},
  'Religious':          { m1: 3, m2: 1, h8: 1, h9: 1,t5:1, t2:1, h2:2,h3:1,h4:2,h5:2,h6:2,h13:2,h16:3,h18:3,h19:3 },
  'Magical':            { h16:3,h18:3,h19:3, alchemists: 2,t19:5, watchmaker:2, alchemists:1},
  'Military':           { h11: 2, h13: 2, h6: 2,forge:2,alchemists:1},
  'Industry':           { t5: 3, h7: 3, h10: 2, h11: 2, alchemists:3,forge:3},
  'Entertainment':      { h8: 2, h9: 2, t5:2, h15:1},
  default:              { },
}

const FIT_FACTOR     = 0.92    // a model must fit within this fraction of the plot footprint
const FIT_TOLERANCE  = 0.12    // models within this coverage of the best fit are randomised between

// ── BuildingRenderer ──────────────────────────────────────────────────────────
// Places one street-facing model in the front half of each plot, using the plot's
// recorded streetEdges to find the frontage. Every plot gets a GLB model (closest
// fit); there are no procedural box houses.

const GROUND_Y = 0.075   // plot-fill surface height (see PlotRenderer); buildings seat here

// Back-yard trees: plots whose building leaves empty space behind it get small trees
// scattered in the back (never on the street-facing front).
const TREE_GLB            = '/resources/tree.glb'
const TREE_MIN_BACK_DEPTH = 0.08   // empty depth behind the building required to add trees
const TREE_SPACING        = 0.07   // back-yard scatter grid spacing
const TREE_DENSITY        = 0.6    // fraction of grid cells that get a tree
const TREE_MAX_PER_PLOT   = 4
const TREE_MIN_FRONTAGE   = 0.16   // plot frontage below which we skip trees

export default class BuildingRenderer {
  constructor() {
    this.featureManager = null   // lazily created (needs the scene)
    this._lib = null             // PartLibrary once loaded
    this._libPromise = null      // loading promise (singleton)
    this._paraGroups = []        // THREE.Groups added for parametric buildings
    this._renderGen = 0          // incremented each render; async callbacks abort if stale
    this._visible = true         // buildings shown by default; persists across regenerations
  }

  clear(scene) {
    this.featureManager?.clear()
    for (const g of this._paraGroups) scene?.remove(g)
    this._paraGroups = []
  }

  setBuildingsVisible(on) {
    this._visible = on
    for (const g of this._paraGroups) g.visible = on
    if (this.featureManager) {
      for (const obj of this.featureManager._objects) obj.visible = on
    }
  }

  _ensureLib() {
    if (this._libPromise) return this._libPromise
    this._libPromise = new PartLibrary(PARA_LIB_PATH, { worldScale: PARA_SCALE }).load()
      .then(lib => { this._lib = lib; return lib })
    return this._libPromise
  }

  // Called by WorldRenderer so async building loads trigger a re-render.
  setDirtyCallback(fn) { this._markDirty = fn }

  render(scene, plots, districtData) {
    const gen = ++this._renderGen
    this.clear(scene)
    if (!plots?.length) return
    if (!this.featureManager) this.featureManager = new FeatureManager(scene)

    const districtById = new Map((districtData?.districts || []).map(d => [d.id, d]))
    const housePlacements = []
    const paraQueue = []   // { spec, x, z, rotY } — assembled once the PartLibrary is ready

    for (const plot of plots) {
      if (plot.blockType === 'square') continue   // paved squares grow no house
      const district = districtById?.get(plot.districtId)
      if (this._isParametric(district)) {
        const entry = this._spawnParametric(plot, district, housePlacements)
        if (entry) paraQueue.push(entry)
      } else {
        this._spawn(plot, housePlacements, districtById)
      }
    }
    // Landmarks are placed by the server before plots (ADR-0005); here we just render
    // the recorded placements.
    for (const lb of (districtData?.landmarkBuildings || [])) {
      const m = MODEL_BY_NAME.get(lb.name)
      if (m) housePlacements.push({ x: lb.x, z: lb.z, rotY: lb.rotY ?? 0, glbPath: m.glbPath, scale: MODEL_SCALE })
    }
    if (housePlacements.length) {
      this.featureManager.spawnBuildings(housePlacements, GROUND_Y).then(() => {
        if (this._renderGen !== gen) return
        if (!this._visible) for (const obj of this.featureManager._objects) obj.visible = false
        this._markDirty?.()
      })
    }

    if (paraQueue.length) {
      this._ensureLib().then(lib => {
        if (this._renderGen !== gen) return   // superseded by a newer render call
        for (const { spec, x, z, rotY } of paraQueue) {
          const g = assemble(spec, lib)
          g.scale.setScalar(PARA_SCALE)
          g.position.set(x, GROUND_Y, z)
          g.rotation.y = rotY
          g.visible = this._visible
          scene.add(g)
          this._paraGroups.push(g)
        }
        this._markDirty?.()
      })
    }
  }

  // Deterministic [0,1) RNG from a seed (stable across rebuilds).
  _rand(seed) {
    let s = (seed * 2654435761) >>> 0
    s ^= s << 13; s ^= s >>> 17; s ^= s << 5
    return (s >>> 0) / 0x100000000
  }

  // District type → weight-matrix key.
  _districtKey(district) {
    const type = district?.assignedType
    if (!type) return 'default'
    if (type === 'Residential') return `Residential-${district.residentialClass ?? 'Middle'}`
    if (type === 'Leadership') return 'Leadership'
    return type
  }

  // Pick a model for a plot of footprint bw×bd in the given district. Models are
  // placed at their natural size (MODEL_SCALE), never stretched. Every plot gets a
  // model — as close to a fit as possible: models that fit within FIT_FACTOR are
  // preferred (best coverage wins, with FIT_TOLERANCE-banded ties randomised), and
  // if none fit the least-overflowing model is used. When the district has no
  // weighted models (empty/missing list), every model is eligible so a closest fit
  // is still found. Returns { glbPath } (null only if no models exist at all).
  _selectModel(district, bw, bd, seed) {
    let weights = DISTRICT_MODEL_WEIGHTS[this._districtKey(district)] || DISTRICT_MODEL_WEIGHTS.default
    if (!weights || Object.keys(weights).length === 0) {
      weights = Object.fromEntries([...MODEL_BY_NAME.keys()].map(name => [name, 1]))
    }
    const fitW = bw * FIT_FACTOR, fitD = bd * FIT_FACTOR
    const fitting = []      // models that fit inside the plot: { glbPath, w, cov }
    const overflowing = []  // models too big: { glbPath, over }  (over = how far past the plot)
    let bestCov = 0
    for (const name in weights) {
      const w = weights[name]
      const m = MODEL_BY_NAME.get(name)
      if (!w || w <= 0 || !m) continue
      const mw = m.width * MODEL_SCALE, md = m.depth * MODEL_SCALE   // world footprint at fixed scale
      const over = Math.max(0, mw - fitW) + Math.max(0, md - fitD)   // 0 = fits (front faces the street)
      if (over <= 0) {
        const cov = (mw * md) / (bw * bd)
        fitting.push({ glbPath: m.glbPath, w, cov })
        if (cov > bestCov) bestCov = cov
      } else {
        overflowing.push({ glbPath: m.glbPath, over })
      }
    }
    if (fitting.length) {
      const close = fitting.filter(c => c.cov >= bestCov - FIT_TOLERANCE)
      const total = close.reduce((s, c) => s + c.w, 0)
      let r = this._rand(seed) * total
      for (const c of close) { if ((r -= c.w) <= 0) return { glbPath: c.glbPath } }
      return { glbPath: close[0].glbPath }
    }
    if (overflowing.length) {   // nothing fits — use the model closest to fitting
      overflowing.sort((a, b) => a.over - b.over)
      return { glbPath: overflowing[0].glbPath }
    }
    return null
  }

  // True for district types that should use Parametric Buildings instead of fixed GLBs.
  _isParametric(district) {
    return district?.assignedType === 'Residential'
  }

  // Build a { spec, x, z, rotY } entry for a parametric residential building.
  // Returns null if the plot is too small to build on.
  _spawnParametric(plot, district, housePlacements) {
    const poly = plot.blockCorners
    const streetEdges = plot.streetEdges || []
    if (!poly || poly.length < 3 || streetEdges.length === 0) return null

    // Primary frontage = longest street-facing edge (same logic as _spawn).
    let a = null, b = null, len = -1
    for (const se of streetEdges) {
      const va = poly[se.index], vb = poly[(se.index + 1) % poly.length]
      if (!va || !vb) continue
      const l = Math.hypot(vb.x - va.x, vb.y - va.y)
      if (l > len) { len = l; a = va; b = vb }
    }
    if (!a || len < 0.06) return null

    const ex = (b.x - a.x) / len, ey = (b.y - a.y) / len
    let nx = -ey, ny = ex
    let cx = 0, cy = 0
    for (const v of poly) { cx += v.x; cy += v.y }
    cx /= poly.length; cy /= poly.length
    const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2
    if ((cx - mx) * nx + (cy - my) * ny < 0) { nx = -nx; ny = -ny }

    let depth = 0
    for (const v of poly) { const d = (v.x - a.x) * nx + (v.y - a.y) * ny; if (d > depth) depth = d }

    const distKey = this._districtKey(district)
    // Townhouse districts occupy a fixed front portion; others fill most of the plot.
    const isRow = distKey.includes('Noble') || distKey.includes('Middle')
    const worldBw = len * 0.90                                    // full frontage width (shared wall style)
    const worldBd = isRow ? Math.min(depth * 0.45, 3.0) : Math.min(depth * 0.50, worldBw * 1.5) * 0.9
    if (worldBw < 0.06 || worldBd < 0.05) return null

    const setback = Math.min(0.04, depth * 0.10)
    const x = mx + nx * (setback + worldBd / 2)
    const z = my + ny * (setback + worldBd / 2)
    const rotY = Math.atan2(-nx, -ny)

    // Convert world dimensions to model units (assemble() works in model space; PARA_SCALE applied later).
    const bw = worldBw / PARA_SCALE, bd = worldBd / PARA_SCALE
    const spec = this._buildSpec(distKey, bw, bd, x, z)
    if (housePlacements) {
      this._scatterBackTrees(plot, poly, mx, my, ex, ey, nx, ny, len, setback + worldBd, depth, housePlacements)
    }
    return { spec, x, z, rotY }
  }

  // Build a deterministic Building Spec for a residential plot.
  _buildSpec(distKey, bw, bd, worldX, worldZ) {
    const hash = posHash(worldX, worldZ)
    const r0 = this._rand(hash),     r1 = this._rand(hash + 7)
    const r2 = this._rand(hash + 13), r3 = this._rand(hash + 19)
    const r4 = this._rand(hash + 23), r5 = this._rand(hash + 29)

    const style = DISTRICT_BUILDING_STYLES[distKey] ?? DEFAULT_BUILDING_STYLE

    // floors — weighted pick (entries iterated in definition order)
    let floors = 1, floorCum = 0
    for (const [f, w] of Object.entries(style.floors)) {
      floorCum += w
      floors = parseInt(f)
      if (r0 < floorCum) break
    }

    // wall materials
    const nonstone = r1 < style.woodChance ? 'wood' : 'plaster'
    const stone    = r4 < style.graniteChance ? 'granite' : 'stone'
    let wallMaterial
    if (r2 < style.stoneChance) {
      wallMaterial = (r3 < style.mixedChance && floors > 1)
        ? Array.from({ length: floors }, (_, f) => f === 0 ? stone : nonstone)
        : Array.from({ length: floors }, () => stone)
    } else {
      wallMaterial = Array.from({ length: floors }, () => nonstone)
    }

    // roof material — weighted pick
    let roofMat = 'thatch', roofCum = 0
    for (const [mat, w] of Object.entries(style.roof)) {
      roofCum += w
      roofMat = mat
      if (r5 < roofCum) break
    }

    return {
      seed: hash,
      floors,
      footprint: { type: 'wings', wings: [{ minX: -bw / 2, maxX: bw / 2, minZ: -bd / 2, maxZ: bd / 2, dormersOnMinSide: true }] },
      wallMaterial,
      roof: { shape: 'gable', material: roofMat, pitch: 0.40 + r0 * 0.45, overhangMin: style.overhangMin, overhangMax: style.overhangMax },
      suppressedFaces: [],   // server will populate this for townhouse adjacency
    }
  }

  // Record a placement for a district-appropriate model in this plot's front half.
  _spawn(plot, housePlacements, districtById) {
    const poly = plot.blockCorners
    const streetEdges = plot.streetEdges || []
    if (!poly || poly.length < 3 || streetEdges.length === 0) return

    // Primary frontage = longest street-facing edge.
    let a = null, b = null, len = -1
    for (const se of streetEdges) {
      const va = poly[se.index], vb = poly[(se.index + 1) % poly.length]
      if (!va || !vb) continue
      const l = Math.hypot(vb.x - va.x, vb.y - va.y)
      if (l > len) { len = l; a = va; b = vb }
    }
    if (!a || len < 0.06) return

    // Edge direction and inward normal.
    const ex = (b.x - a.x) / len, ey = (b.y - a.y) / len
    let nx = -ey, ny = ex
    let cx = 0, cy = 0
    for (const v of poly) { cx += v.x; cy += v.y }
    cx /= poly.length; cy /= poly.length
    const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2
    if ((cx - mx) * nx + (cy - my) * ny < 0) { nx = -nx; ny = -ny }   // point into the plot

    // Plot depth perpendicular to the frontage.
    let depth = 0
    for (const v of poly) {
      const d = (v.x - a.x) * nx + (v.y - a.y) * ny
      if (d > depth) depth = d
    }

    const bw = len * 0.72
    const bd = Math.min(depth * 0.5, bw * 1.5) * 0.9   // front ~half, not absurdly deep
    if (bw < 0.06 || bd < 0.05) return

    const setback = Math.min(0.04, depth * 0.12)
    const ccx = mx + nx * (setback + bd / 2)
    const ccy = my + ny * (setback + bd / 2)
    const theta = Math.atan2(-nx, -ny)   // local +Z → outward (worldX=-nx, worldZ=-ny)

    // Every plot gets a district-appropriate model (closest fit), placed at the
    // footprint centre and seated on the ground. No procedural box houses. Seeded by
    // position (not plot id) so the choice is stable when neighbouring districts change.
    const sel = this._selectModel(districtById?.get(plot.districtId), bw, bd, posHash(ccx, ccy))
    if (sel) housePlacements.push({ x: ccx, z: ccy, rotY: theta, glbPath: sel.glbPath, scale: MODEL_SCALE })

    // A large/deep plot leaves empty yard behind the building — scatter small trees there.
    this._scatterBackTrees(plot, poly, mx, my, ex, ey, nx, ny, len, setback + bd, depth, housePlacements)
  }

  // Scatter small trees in the back of a plot (perpendicular distance from `frontDepth`
  // to the plot's full `depth`), skipped unless the back yard is sizeable. `frontDepth`
  // is the building's back edge, so trees never land on the street-facing front.
  _scatterBackTrees(plot, poly, mx, my, ex, ey, nx, ny, len, frontDepth, depth, placements) {
    const backStart = frontDepth + 0.04
    if (depth - backStart < TREE_MIN_BACK_DEPTH || len < TREE_MIN_FRONTAGE) return
    const halfLen = len / 2 - 0.03
    let placed = 0
    for (let d = backStart; d < depth - 0.03 && placed < TREE_MAX_PER_PLOT; d += TREE_SPACING) {
      for (let l = -halfLen; l <= halfLen && placed < TREE_MAX_PER_PLOT; l += TREE_SPACING) {
        // Seed by the (un-jittered) world cell position so trees are stable across
        // regenerations, independent of plot id.
        const seed = posHash(mx + ex * l + nx * d, my + ey * l + ny * d)
        if (this._rand(seed) > TREE_DENSITY) continue
        const ll = l + (this._rand(seed + 1) - 0.5) * TREE_SPACING * 0.7
        const dd = d + (this._rand(seed + 2) - 0.5) * TREE_SPACING * 0.7
        const px = mx + ex * ll + nx * dd
        const pz = my + ey * ll + ny * dd
        if (!pointInPolygon(px, pz, poly)) continue
        const scale = 0.13 + this._rand(seed + 3) * 0.08   // small
        placements.push({ x: px, z: pz, rotY: this._rand(seed + 4) * Math.PI * 2, glbPath: TREE_GLB, scale })
        placed++
      }
    }
  }
}
