export const nameLibraryData = {
  "global": {
    "adjectives": [
      "Ancient", "Ashen", "Bitter", "Blighted", "Broken", "Burning", "Cold", "Crimson",
      "Cursed", "Dark", "Dead", "Dying", "Ember", "Eternal", "Fallen", "Forgotten",
      "Frozen", "Grim", "Hallowed", "Haunted", "Hidden", "High", "Iron", "Ivory",
      "Jagged", "Last", "Lost", "Misty", "Moonlit", "Obsidian", "Old", "Pale",
      "Ruined", "Sacred", "Scarred", "Shadow", "Shattered", "Silent", "Silver",
      "Sinister", "Skeletal", "Smouldering", "Sorrow", "Sunken", "Tainted",
      "Twilight", "Undying", "Veiled", "Verdant", "Whispered", "Wretched",
      "Amber", "Bleak", "Boundless", "Dire", "Dread", "Dusk", "Elder",
      "Fading", "Gilded", "Gloom", "Hollow", "Lifeless", "Murky", "Nethered",
      "Ravaged", "Smoked", "Spectral", "Stained", "Thorned", "Twisted", "Umber",
      "Waning", "Wild", "Windswept", "Withered", "Wraith",
      "Abandoned", "Abyssal", "Aching", "Ageless", "Alabaster", "Barren", "Basalt",
      "Bewitched", "Black", "Bloodied", "Blooming", "Blue", "Bramble", "Brazen",
      "Brimstone", "Brindled", "Brittle", "Bronze", "Brooding", "Burnished",
      "Charred", "Chilled", "Coiled", "Copper", "Corroded", "Craggy", "Crooked",
      "Crumbling", "Crystal", "Dappled", "Darkened", "Deathless", "Deep", "Defiant",
      "Desolate", "Devouring", "Distant", "Dormant", "Doomed", "Dreaming",
      "Drifting", "Drowned", "Dun", "Dusty", "Ebon", "Echoing", "Empty",
      "Enchanted", "Endless", "Everlasting", "Faded", "Fair", "Faint", "Far",
      "Feral", "Feverish", "Flickering", "Foaming", "Foreboding", "Foul",
      "Frayed", "Frostbitten", "Furrowed", "Ghastly", "Ghostly", "Glacial",
      "Gnarled", "Golden", "Granite", "Grave", "Grey", "Green", "Grieving",
      "Groaning", "Guarded", "Harrowed", "Heavy", "Honeyed", "Howling",
      "Icebound", "Idle", "Immense", "Infernal", "Infested", "Inky", "Insatiable",
      "Jade", "Jealous", "Keening", "Knotted", "Lamenting", "Languid", "Leaden",
      "Leaning", "Lichened", "Lightless", "Loamy", "Lonely", "Lonesome",
      "Looming", "Lowly", "Luminous", "Malachite", "Marbled", "Mired", "Molten",
      "Mossy", "Mournful", "Mute", "Nameless", "Narrow", "Nightbound", "Noxious",
      "Numb", "Onyx", "Overgrown", "Petrified", "Phantom", "Pitted", "Poisoned",
      "Polished", "Quartz", "Raging", "Rasping", "Reeking", "Restless", "Rimed",
      "Roaring", "Rotted", "Rugged", "Rusted", "Salted", "Sandstone", "Scorched",
      "Screaming", "Seared", "Serpentine", "Shifting", "Shivering", "Shrieking",
      "Shrouded", "Slate", "Sleepless", "Slumbering", "Smoky", "Somber", "Sooty",
      "Sour", "Splintered", "Steaming", "Stone", "Sulphurous", "Sundered",
      "Sunless", "Swirling", "Tangled", "Tarnished", "Tempered", "Thistled",
      "Thundering", "Timeworn", "Tumbled", "Unbroken", "Unhallowed", "Unhewn",
      "Unseen", "Vaulted", "Vengeful", "Vermillion", "Vile", "Voiceless",
      "Wailing", "Warped", "Wasted", "Watchful", "Weathered", "Weeping",
      "White", "Wintry", "Withering", "Yellowed"
    ],
    "dramaticNouns": [
      "Ashes", "Betrayal", "Calamity", "Chaos", "Conquest", "Curse", "Decay",
      "Desolation", "Despair", "Doom", "Dread", "Dust", "Ending", "Exile",
      "Fate", "Fear", "Flame", "Fog", "Fury", "Gloom", "Grief", "Hatred",
      "Judgement", "Lament", "Madness", "Malice", "Misery", "Mourning",
      "Oblivion", "Peril", "Plague", "Prophecy", "Rage", "Regret", "Ruin",
      "Shadow", "Silence", "Sin", "Sorrow", "Suffering", "Tempest", "Terror",
      "Torment", "Twilight", "Vengeance", "Woe", "Wrath", "Agony", "Blight",
      "Catastrophe", "Corruption", "Darkness", "Devastation", "Discord",
      "Dusk", "Eternity", "Fallen Dreams", "Forgetting", "Ferocity", "Havoc",
      "Isolation", "Loss", "Malevolence", "Mystery", "Nightfall", "Penance",
      "Perdition", "Penitence", "Reckoning", "Redemption", "Retribution",
      "Sacrifice", "Salvation", "Solitude", "Tribulation", "Undoing", "Whispers",
      "Absolution", "Affliction", "Anguish", "Annihilation", "Apocalypse",
      "Ascension", "Banishment", "Bloodshed", "Bondage", "Captivity", "Cataclysm",
      "Collapse", "Condemnation", "Cruelty", "Damnation", "Deception", "Defeat",
      "Delirium", "Deliverance", "Demise", "Denial", "Desecration", "Disaster",
      "Disgrace", "Dissolution", "Downfall", "Dreams", "Drought", "Ecstasy",
      "Emptiness", "Enmity", "Envy", "Extinction", "Famine", "Fracture",
      "Frenzy", "Genesis", "Glory", "Grace", "Guilt", "Heresy", "Hope",
      "Hunger", "Hysteria", "Ignominy", "Ill Fortune", "Illusion", "Imprisonment",
      "Infamy", "Inheritance", "Insurrection", "Longing", "Lunacy", "Martyrdom",
      "Memory", "Mercy", "Miracles", "Mischief", "Nightmares", "Obscurity",
      "Omens", "Passage", "Passion", "Pestilence", "Pilgrimage", "Ransom",
      "Rapture", "Rebellion", "Recompense", "Requiem", "Resurrection",
      "Revelation", "Revolt", "Ruination", "Sanctuary", "Scorn", "Sedition",
      "Shame", "Silence Eternal", "Slaughter", "Sorcery", "Splendor", "Storms",
      "Strife", "Submission", "Surrender", "Temptation", "Trials", "Triumph",
      "Turmoil", "Tyranny", "Unrest", "Vanity", "Vigil", "Wandering", "Warfare",
      "Wastes", "Yearning", "Zeal"
    ],
    "properNames": [
      "Aethon", "Aldric", "Ashenvale", "Azgoth", "Baelor", "Blackmoor",
      "Bloodstone", "Brightholm", "Caerwyn", "Coldwater", "Dalaran", "Darkshire",
      "Dawnmere", "Drakmor", "Duskhaven", "Duskwood", "Eldenmoor", "Emberglass",
      "Fangorn", "Flamereach", "Gareth", "Greymist", "Grimhold", "Grimmoor",
      "Highrock", "Ironforge", "Keldor", "Khazad", "Lhûn", "Lorwyn",
      "Mirkwood", "Mordaunt", "Mordor", "Morvaine", "Mythwind", "Neldor",
      "Norrath", "Oberon", "Raveloft", "Ravenwall", "Redcliff", "Rhenost",
      "Rivendell", "Saltmere", "Shadowfen", "Silverhold", "Silvermoon",
      "Sindrel", "Stonemist", "Stromgarde", "Sunwell", "Swiftmire",
      "Thornwall", "Tirith", "Tirsfal", "Ulduar", "Undercroft", "Valdris",
      "Valyria", "Vendrik", "Westfall", "Whitehaven", "Wyrmscar", "Xandrel",
      "Yharnam", "Zuldazar",
      "Aerthorn", "Ambervale", "Arkendale", "Ashfall", "Baelfire", "Balehold",
      "Blackspire", "Bramblewood", "Briarcliff", "Brindlemoor", "Cairnmoor",
      "Cindercliff", "Crowmere", "Deepwater", "Doomhaven", "Dragomir",
      "Draugmoor", "Duskfall", "Eldrin", "Everholt", "Fallowmere", "Farrowdale",
      "Frosthollow", "Galewind", "Gorathol", "Graywatch", "Hallowmere",
      "Harrowgate", "Hollowmere", "Icebrook", "Kaelthorn", "Kalvaris",
      "Karthos", "Kelmoor", "Larkspire", "Ledmoor", "Lorendal", "Marrowfen",
      "Melgorn", "Mireholt", "Morrowind", "Nightfell", "Nordholm", "Northaven",
      "Oakenshire", "Orinmoor", "Pallenrock", "Quorwyn", "Ravenscar",
      "Rimewatch", "Rookmoor", "Rothgar", "Saldris", "Selwyn", "Shalendra",
      "Sorrowmarch", "Stormwatch", "Talvaris", "Thanewick", "Thornfield",
      "Torvald", "Umbermoor", "Valgrave", "Vaelith", "Veymoor", "Vorindel",
      "Wintermere", "Wolfmere", "Wyrmfall", "Yorwick"
    ],
    "occupations": [
      "Alchemists", "Artificers", "Assassins", "Bankers", "Bards",
      "Blacksmiths", "Brewers", "Carpenters", "Cartographers", "Conjurers",
      "Courtesans", "Cutthroats", "Diviners", "Dyers", "Enchanters",
      "Farmers", "Fishers", "Fletchers", "Forgers", "Gamblers", "Glaziers",
      "Gravediggers", "Heralds", "Herbalists", "Hunters", "Illusionists",
      "Innkeepers", "Jewellers", "Jugglers", "Knights", "Lumberjacks",
      "Masons", "Merchants", "Mercenaries", "Miners", "Monks", "Navigators",
      "Necromancers", "Painters", "Physicians", "Poisoners", "Potters",
      "Priests", "Reapers", "Rogues", "Sailors", "Scholars", "Scribes",
      "Shapers", "Slayers", "Smiths", "Smugglers", "Soldiers", "Sorcerers",
      "Spies", "Tailors", "Tanners", "Thieves", "Tinkers", "Traders",
      "Trappers", "Warlocks", "Weavers", "Witches", "Wizards", "Wranglers",
      "Apothecaries", "Archers", "Armourers", "Astrologers", "Beekeepers",
      "Bookbinders", "Bounty Hunters", "Butchers", "Chandlers", "Chroniclers",
      "Clerics", "Coopers", "Coppersmiths", "Cutters", "Diggers", "Dockhands",
      "Ferrymen", "Foragers", "Gemcutters", "Glassblowers", "Gravekeepers",
      "Grooms", "Guards", "Guides", "Harvesters", "Healers", "Hermits",
      "Interpreters", "Jesters", "Keepers", "Launderers", "Lookouts",
      "Marauders", "Mediums", "Messengers", "Millers", "Minstrels", "Nomads",
      "Oracles", "Outriders", "Pilgrims", "Pirates", "Prospectors", "Ragmen",
      "Ratcatchers", "Ropemakers", "Saboteurs", "Saddlers", "Sages",
      "Scavengers", "Sculptors", "Seers", "Sentinels", "Shepherds",
      "Shipwrights", "Skinners", "Stewards", "Stonecutters", "Surveyors",
      "Swordsmiths", "Tamers", "Tinsmiths", "Undertakers", "Vintners",
      "Wardens", "Watchmen", "Wheelwrights", "Woodcarvers"
    ],
    "districtSuffixes": [
      "Arcade", "Burrow", "Cross", "District", "End", "Exchange",
      "Fields", "Gate", "Green", "Grounds", "Haven", "Hold",
      "Lane", "Market", "Mews", "Parish", "Passage", "Quarter",
      "Row", "Run", "Side", "Square", "Street", "Terrace",
      "Vale", "Ward", "Way", "Wharf", "Yard", "Zone",
      "Alley", "Bank", "Bend", "Bridge", "Circle", "Close", "Common",
      "Court", "Crescent", "Crossing", "Dell", "Ditch", "Dock", "Enclave",
      "Esplanade", "Flats", "Gardens", "Gate End", "Harbor", "Height",
      "Hill", "Junction", "Landing", "Loop", "Meadow", "Mile", "Nook",
      "Path", "Point", "Precinct", "Quay", "Reach", "Ridge", "Ring",
      "Rise", "Sanctuary", "Shore", "Slope", "Stair", "Steps", "Trace",
      "Tract", "Trail", "Turn", "Vault", "Verge", "Walk", "Warren",
      "Wynd", "Yardage"
    ],
    "terrainSuffixes": [
      "Area", "Country", "Domain", "Expanse", "Frontier", "Lands",
      "Reaches", "Region", "Territory", "Tract", "Vale", "Wilds", "Zone",
      "Basin", "Belt", "Border", "Bounds", "Corridor", "Expanses", "Fringe",
      "Hinterland", "Marches", "Outskirts", "Plateau", "Province", "Range",
      "Realm", "Span", "Stretch", "Sward", "Verge", "Waste", "Wilderness"
    ]
  },
  "terrain": {
    "Forest":    { "nouns": ["Arboretum", "Canopy", "Copse", "Dell", "Forest", "Greenwood", "Grove", "Glade", "Thicket", "Timberland", "Weald", "Wildwood", "Wood", "Woodland",
      "Boscage", "Brake", "Brush", "Coppice", "Firwood", "Gladewood", "Hollow", "Hurst", "Oakwood", "Pinewood", "Shaw", "Spinney", "Underwood", "Verderwood", "Wildgrove", "Wold"] },
    "Mountains": { "nouns": ["Bastions", "Crags", "Escarpment", "Heights", "Massif", "Mountains", "Peaks", "Pinnacles", "Ramparts", "Range", "Ridge", "Spires", "Summit", "Teeth",
      "Alps", "Battlements", "Buttress", "Cairns", "Cliffside", "Colossus", "Crown", "Highpeaks", "Horns", "Palisade", "Precipices", "Steeps", "Tors", "Wall"] },
    "Hills":     { "nouns": ["Barrows", "Bluffs", "Downs", "Drumlins", "Fells", "Hills", "Hummocks", "Knolls", "Moors", "Ridges", "Rises", "Tor", "Uplands",
      "Brae", "Foothills", "Heath", "Hillocks", "Knap", "Mounds", "Rolling Downs", "Scarps", "Slopes", "Swells", "Wolds"] },
    "Plains":    { "nouns": ["Barrens", "Flatlands", "Flats", "Grassland", "Lowlands", "Meadows", "Plains", "Prairie", "Savannah", "Steppe", "Tundra", "Veldt",
      "Downland", "Expanse", "Fields", "Flatland", "Grasses", "Greens", "Heartland", "Lowfields", "Sward", "Vale", "Vega"] },
    "Swamp":     { "nouns": ["Bogs", "Deltas", "Fens", "Marshes", "Mere", "Mire", "Morass", "Mudflats", "Murk", "Quagmire", "Slough", "Swamps", "Wetlands",
      "Bayou", "Bottoms", "Fenland", "Marish", "Mireland", "Mudlands", "Peatland", "Quag", "Reedbeds", "Sump"] },
    "Sea":       { "nouns": ["Abyss", "Bay", "Brine", "Channel", "Current", "Deep", "Deeps", "Depths", "Gulf", "Maelstrom", "Ocean", "Sea", "Strait", "Surge", "Tide", "Waters",
      "Basin", "Billows", "Fathoms", "Main", "Reef", "Shoals", "Swell", "Trench", "Waves", "Whirlpool"] },
    "Lake":      { "nouns": ["Basin", "Fen", "Lake", "Loch", "Mere", "Mirror", "Pool", "Reservoir", "Shallows", "Tarn", "Waters",
      "Cove", "Inlet", "Lagoon", "Millpond", "Pond", "Sound", "Spring", "Still"] },
    "River":     { "nouns": ["Brook", "Channel", "Current", "Delta", "Flow", "Narrows", "River", "Run", "Rush", "Stream", "Torrent", "Tributary", "Wade",
      "Cascade", "Confluence", "Course", "Creek", "Ford", "Rapids", "Rill", "Waterway"] },
    "Cliff":     { "nouns": ["Bluffs", "Brow", "Cliffs", "Crags", "Escarpment", "Face", "Ledge", "Overhang", "Precipice", "Scarp", "Shelf", "Spur", "Walls",
      "Bastion", "Buttress", "Crest", "Headland", "Palisades", "Rampart", "Rimrock", "Verge"] },
    "Ice Sheet": {
      "adjectives": ["Frozen", "Glacial", "Arctic", "Pale", "Silent", "Shattered", "Eternal", "Bleak", "Endless", "White", "Bitter", "Howling", "Sunless", "Drifting", "Desolate", "Crystal", "Polar", "Windswept", "Barren", "Stark",
        "Frostbound", "Glassy", "Icebound", "Numbing", "Permafrost", "Rimed", "Shivering", "Sleeting", "Snowbound", "Winterworn"],
      "nouns": ["Wastes", "Expanse", "Flats", "Sheet", "Tundra", "Fields", "Reaches", "Shelf", "Plain", "Drift", "Barrens", "Stillness", "Silence", "Glacier", "Frost", "Cap", "Plateau", "Void", "Icefields", "Frostmere",
        "Floe", "Frostlands", "Icebreak", "Icecap", "Iceplain", "Rime", "Snowfields", "Snowplain", "Whiteout", "Winterlands"]
    }
  },
  "edge": {
    "River": { "nouns": ["Brook", "Current", "Flow", "River", "Run", "Rush", "Stream", "Torrent",
      "Cascade", "Confluence", "Course", "Creek", "Ford", "Rapids", "Rill", "Tributary", "Wade", "Waterway", "Watercourse", "Freshet"] },
    "Cliff": { "nouns": ["Bluffs", "Cliffs", "Crags", "Escarpment", "Precipice", "Scarp", "Walls",
      "Bastion", "Brow", "Buttress", "Crest", "Face", "Headland", "Ledge", "Overhang", "Palisades", "Rampart", "Rimrock", "Shelf", "Spur", "Verge"] }
  },
  "district": {
    "Market":        { "adjectives": ["Amber", "Bustling", "Coin", "Eastern", "Foreign", "Gilded", "Golden", "Grand", "Jewel", "Northern", "Silk", "Silver", "Southern", "Spice", "Trade", "Western",
      "Copper", "Crowded", "Distant", "Exotic", "Fine", "Flourishing", "Hawking", "Imported", "Lively", "Loud", "Lucrative", "Merchant", "Opulent", "Prosperous", "Rich", "Roaring",
      "Sprawling", "Teeming", "Thriving", "Vibrant", "Wealthy", "Bartering", "Brimming", "Clamorous", "Festive", "Overflowing", "Rowdy", "Sumptuous", "Bountiful", "Colourful"],
      "nouns": ["Arcade", "Bazaar", "Emporium", "Exchange", "Forum", "Hall", "Market", "Mart", "Souk", "Square",
      "Agora", "Auction House", "Bourse", "Caravanserai", "Concourse", "Crossroads", "Depot", "Fairground", "Marketplace", "Mercantile",
      "Pavilion", "Plaza", "Row", "Stalls", "Trade Hall", "Trading Post", "Warehouse", "Emporia", "Trading Floor", "Bazaar Row"] },
    "Military":      { "adjectives": ["Battle", "Blood", "Crimson", "Drake", "Eagle", "Fist", "Fortress", "Iron", "Knight", "Legion", "Shield", "Steel", "Stone", "Thunder", "War",
      "Armoured", "Ashen", "Banner", "Bastion", "Blade", "Bulwark", "Command", "Falcon", "Gauntlet", "Grey", "Hawk", "Ironclad", "Lance", "Lion", "Marching",
      "Onyx", "Phalanx", "Raven", "Rampart", "Sentinel", "Siege", "Spear", "Standard", "Steadfast", "Sworn", "Tower", "Vanguard", "Warrior", "Watch", "Wolf"],
      "nouns": ["Armory", "Barracks", "Bastion", "Citadel", "Fastness", "Fort", "Garrison", "Keep", "Rampart", "Stronghold",
      "Arsenal", "Battlement", "Blockhouse", "Bulwarks", "Camp", "Compound", "Depot", "Encampment", "Fortification", "Guardhouse",
      "Muster", "Outpost", "Parade Ground", "Redoubt", "Ringfort", "Sconce", "Stockade", "Tower", "Watchpost", "Fortalice"] },
    "Residential":   { "adjectives": ["Common", "Crowded", "Humble", "Labouring", "Lower", "Middle", "Old", "Poor", "Quiet", "Simple", "Sleeping", "Teeming", "Toiling", "Upper", "Working",
      "Bustling", "Close-Knit", "Cramped", "Domestic", "Faded", "Familial", "Grey", "Homely", "Humdrum", "Inner", "Meager", "Modest", "Narrow", "Ordinary", "Outer",
      "Overcrowded", "Peaceful", "Plain", "Quaint", "Rustic", "Settled", "Shabby", "Sheltered", "Small", "Sober", "Steady", "Tidy", "Weathered", "Weary"],
      "nouns": ["Burrow", "Commons", "Hearths", "Hovels", "Quarters", "Rows", "Rookery", "Tenements", "Warrens",
      "Alleys", "Blocks", "Cottages", "Courts", "Dwellings", "Flats", "Homesteads", "Houses", "Lanes", "Lodgings",
      "Longhouses", "Nooks", "Row Houses", "Shanties", "Terraces", "Yards", "Garrets", "Cellars"] },
    "Entertainment": { "adjectives": ["Dancing", "Gilded", "Joyful", "Laughing", "Merry", "Painted", "Pleasant", "Revelling", "Singing", "Velvet", "Wandering", "Whispering", "Wild",
      "Boisterous", "Bright", "Carnival", "Charming", "Colourful", "Dazzling", "Delightful", "Enchanting", "Festive", "Flamboyant", "Glittering", "Gleeful", "Jesting",
      "Jolly", "Lantern-Lit", "Lush", "Musical", "Playful", "Riotous", "Roguish", "Sparkling", "Theatrical", "Twinkling", "Vivid", "Whimsical"],
      "nouns": ["Carnival", "Circus", "Gardens", "Grounds", "Hall", "Parlour", "Pavilion", "Stage", "Theatre", "Walk",
      "Amphitheatre", "Arena", "Boardwalk", "Cabaret", "Fairgrounds", "Gallery", "Menagerie", "Music Hall", "Opera House", "Playhouse",
      "Promenade", "Revel Grounds", "Salon", "Showhouse", "Tavern Row", "Tent Row", "Amusements", "Festival Grounds"] },
    "Religious":     { "adjectives": ["Blessed", "Divine", "Eternal", "Faithful", "Hallowed", "Holy", "Pure", "Sacred", "Sanctified", "Serene", "Vigilant",
      "Angelic", "Benevolent", "Celestial", "Consecrated", "Devout", "Ecclesiastic", "Ethereal", "Exalted", "Godly", "Heavenly", "Immaculate", "Luminous",
      "Penitent", "Pious", "Radiant", "Reverent", "Sainted", "Solemn", "Transcendent", "Venerable", "Worshipful"],
      "nouns": ["Abbey", "Altars", "Cathedral", "Chapel", "Cloister", "Monastery", "Sanctuary", "Sanctum", "Shrine", "Temple",
      "Basilica", "Chantry", "Convent", "Fane", "Hermitage", "House of Worship", "Minster", "Oratory", "Pantheon", "Priory",
      "Reliquary", "Sacristy", "Seminary", "Spire", "Tabernacle", "Vestry", "Vigil Hall", "Chapterhouse"] },
    "Magical":       { "adjectives": ["Arcane", "Astral", "Dreaming", "Eldritch", "Enchanted", "Ether", "Ethereal", "Fey", "Mystical", "Runic", "Spectral", "Transcendent", "Void", "Weave",
      "Alchemical", "Bewitched", "Conjured", "Crystalline", "Elemental", "Enigmatic", "Esoteric", "Illusory", "Luminescent", "Mysterious", "Nebulous", "Numinous",
      "Occult", "Otherworldly", "Prismatic", "Rune-Carved", "Sigiled", "Sorcerous", "Spellbound", "Starlit", "Thaumaturgic", "Umbral", "Warded", "Wondrous", "Wyrd"],
      "nouns": ["Conclave", "Conservatory", "Enclave", "Institute", "Nexus", "Sanctum", "Spire", "Tower", "Vault",
      "Academy", "Archive", "Athenaeum", "Chamber", "Circle", "Cloister", "College", "Laboratory", "Library", "Observatory",
      "Repository", "Sanctorum", "Scriptorium", "Study", "Vaultworks", "Workshop", "Font"] },
    "Industry":      { "adjectives": ["Anvil", "Ash", "Bellows", "Coal", "Copper", "Forge", "Hammer", "Iron", "Mill", "Ore", "Slag", "Smoke", "Soot", "Steam", "Stone",
      "Blast", "Bronze", "Cinder", "Clanking", "Clattering", "Cog", "Ember", "Engine", "Flame", "Furnace", "Grinding", "Grimy", "Grease",
      "Ironworks", "Molten", "Piston", "Rattling", "Rivet", "Rust", "Scorched", "Sooty", "Sparking", "Tinker's", "Toiling", "Wheel", "Blackened", "Sweltering"],
      "nouns": ["Foundry", "Furnace", "Mills", "Pit", "Press", "Sheds", "Smelter", "Works", "Workshops", "Yards",
      "Assembly Line", "Cauldron Hall", "Cooperage", "Factory", "Forgeworks", "Kiln", "Loom House", "Machine Hall", "Refinery", "Smithy",
      "Steelworks", "Tannery", "Toolshop", "Vat House", "Warehouses", "Winch Yard", "Wheelhouse", "Millworks", "Bellowshall"] },
    "Leadership":    { "adjectives": ["Grand", "Great", "High", "Imperial", "Majestic", "Noble", "Regal", "Royal", "Sovereign", "Supreme",
      "Absolute", "August", "Commanding", "Crowned", "Dominant", "Exalted", "Glorious", "Governing", "Illustrious", "Lordly",
      "Paramount", "Presiding", "Princely", "Proud", "Reigning", "Resplendent", "Ruling", "Stately", "Storied", "Venerated"],
      "nouns": ["Assembly", "Chamber", "Court", "Hall", "Keep", "Palace", "Sanctum", "Seat", "Throne", "Tower",
      "Bastion", "Capitol", "Citadel", "Council Hall", "Dais", "Manor", "Parliament", "Pavilion", "Presidium", "Rotunda",
      "Rostrum", "Senate", "Spire", "State House", "Stronghold", "Sanctuary", "Legislature", "Audience Hall", "Regency"] },
    "Slums":         { "adjectives": ["Broken", "Crowded", "Dark", "Desperate", "Fallen", "Filthy", "Forgotten", "Grim", "Hollow", "Lowly", "Ruined", "Sunken", "Wretched",
      "Beggared", "Bleak", "Bleeding", "Blighted", "Choked", "Condemned", "Crumbling", "Decrepit", "Derelict", "Dismal", "Downtrodden",
      "Fetid", "Foul", "Grubby", "Hopeless", "Neglected", "Rat-Infested", "Rotten", "Scarred", "Shanty", "Squalid", "Starved", "Tattered", "Threadbare"],
      "nouns": ["Burrow", "Gutter", "Hovels", "Mire", "Pit", "Rookery", "Rows", "Squalor", "Tenements", "Warrens",
      "Alleys", "Backstreets", "Cesspits", "Ditches", "Doss-Houses", "Dredges", "Gutters", "Hollows", "Hovel Row", "Middens",
      "Ruins", "Shackrows", "Shanties", "Slop Yards", "Slumrows", "Squats", "Tanglerows", "Tunnels", "Underholds"] },
    "Noble":         { "adjectives": ["Gilded", "Grand", "High", "Ivory", "Majestic", "Noble", "Proud", "Regal", "Silver", "Stately",
      "Aristocratic", "Cultured", "Distinguished", "Elegant", "Exquisite", "Fashionable", "Genteel", "Graceful", "Illustrious", "Luxurious",
      "Ornate", "Patrician", "Pedigreed", "Pristine", "Refined", "Resplendent", "Sophisticated", "Sumptuous", "Well-Bred", "Wellborn"],
      "nouns": ["Avenue", "Court", "Gardens", "Hall", "Heights", "Manor", "Park", "Row", "Square", "Terrace",
      "Balustrade", "Boulevard", "Chateau", "Circle", "Colonnade", "Crescent", "Estate", "Grand Walk", "Grove", "Mansions",
      "Parade", "Pavilion", "Piazza", "Promenade", "Residence", "Salon", "Townhouses", "Villas", "Vista", "Walkway"] },
    "Monarchy":      { "adjectives": ["Grand", "Imperial", "Majestic", "Royal", "Sovereign",
      "Absolute", "Ancestral", "Crowned", "Dynastic", "Enthroned", "Exalted", "Hereditary", "Regnant", "Reigning", "Supreme"],
      "nouns": ["Court", "Hall", "Keep", "Palace", "Throne",
      "Citadel", "Coronation Hall", "Crown", "Dais", "Dynasty", "Regalia", "Royal Seat", "Scepter", "Sovereignty", "Throne Room"] },
    "Forestry":      { "adjectives": ["Ancient", "Dark", "Deep", "Elder", "Green", "Old", "Shadowed", "Wild",
      "Boughed", "Bramble", "Dense", "Evergreen", "Ferny", "Hushed", "Leafy", "Mossbound", "Overgrown", "Quiet", "Rooted", "Rustling", "Sylvan", "Tangled", "Timbered", "Verdant"],
      "nouns": ["Arboretum", "Copse", "Dell", "Grove", "Timberland", "Wood", "Woodland",
      "Canopy", "Glade", "Greenwood", "Hollow", "Lumberyard", "Sawmill Grounds", "Shaw", "Thicket", "Timberworks", "Treeline", "Weald", "Wildwood", "Woodcamp", "Woodlot"] },
    "Agriculture":   { "adjectives": ["Bountiful", "Fertile", "Golden", "Green", "Humble", "Rich", "Teeming", "Verdant", "Sandy", "Dry", "Grassy", "Minor",
      "Abundant", "Arable", "Blooming", "Bright", "Cultivated", "Flourishing", "Fresh", "Fruitful", "Harvested", "Lush", "Nourishing", "Open",
      "Pastoral", "Plentiful", "Ripe", "Rolling", "Rural", "Seasonal", "Sun-Kissed", "Sweeping", "Thriving", "Yielding"],
      "nouns": ["Fields", "Farmstead", "Grazing", "Harvest", "Meadows", "Pastures", "Plots", "Steading",
      "Acreage", "Barns", "Croft", "Cropland", "Farmhold", "Furrows", "Granary", "Homestead", "Orchard", "Paddocks", "Ranch", "Silos", "Smallholding", "Terraces", "Tillage", "Vineyard"] },
    "Mining":        { "adjectives": ["Deep", "Iron", "Old", "Ore", "Rocky", "Stone", "Sunken", "Silver", "Gold", "Coal", "Shallow", "Sandy", "Dark", "Wet",
      "Boring", "Buried", "Craggy", "Crumbling", "Delved", "Dusty", "Echoing", "Excavated", "Flooded", "Granite", "Hollow", "Jagged", "Ore-Rich",
      "Perilous", "Quarried", "Rugged", "Rumbling", "Scarred", "Slate", "Subterranean", "Sunless", "Tunnelled", "Veined", "Winding", "Cavernous", "Crystalline"],
      "nouns": ["Delve", "Dig", "Excavation", "Mine", "Pit", "Quarry", "Shafts", "Tunnels",
      "Adit", "Bore", "Cavern", "Chasm", "Colliery", "Depths", "Diggings", "Gallery", "Hollows", "Lode", "Ore Works", "Seam", "Shaft Town", "Sinkworks", "Undermine", "Vein"] },
    "Fishing":       { "adjectives": ["Briny", "Cold", "Deep", "Misty", "Silver", "Tidal", "Wet",
      "Brackish", "Breezy", "Coastal", "Foamy", "Salted", "Salty", "Sandy", "Shoreline", "Squally", "Stormy", "Sunlit", "Surging", "Wave-Swept", "Windswept"],
      "nouns": ["Docks", "Harbour", "Landing", "Nets", "Quay", "Shore", "Trawl", "Wharf",
      "Anchorage", "Bay Front", "Boathouse", "Breakwater", "Dockside", "Fishery", "Harbourside", "Jetty", "Mooring", "Net Sheds", "Pier", "Seawall", "Shoreside", "Slipway", "Waterfront"] }
  },
  "godDomains": [
    "War", "Death", "Trade", "Harvest", "Sea", "Sky", "Sun", "Moon",
    "Fire", "Ice", "Earth", "Shadow", "Knowledge", "Fate", "Love",
    "Justice", "Trickery", "Nature", "Forge", "Storm", "Healing",
    "Underworld", "Ancestors", "Time", "Chaos", "Order", "Hunt",
    "Plague", "Wealth", "Dreams", "Fertility", "Madness", "Protection",
    "Air", "Beauty", "Blood", "Bounty", "Change", "Chance", "Craft", "Creation",
    "Cunning", "Darkness", "Dawn", "Deception", "Destiny", "Discord", "Dusk",
    "Endurance", "Fear", "Fortune", "Freedom", "Frost", "Glory", "Gluttony",
    "Greed", "Growth", "Harmony", "Honor", "Illusion", "Ingenuity", "Iron",
    "Joy", "Judgement", "Law", "Life", "Light", "Loyalty", "Luck", "Lust",
    "Memory", "Mercy", "Mischief", "Mountains", "Music", "Oaths", "Pain",
    "Passion", "Patience", "Peace", "Pestilence", "Pride", "Rebirth", "Renewal",
    "Revenge", "Rivers", "Ruin", "Sacrifice", "Secrets", "Silence", "Sleep",
    "Sorrow", "Stars", "Stone", "Strength", "Vengeance", "Victory", "Wanderers",
    "Wind", "Winter", "Wisdom"
  ],
  "godNameParts": {
    "war":       { "prefixes": ["Khal", "Vor", "Grak", "Mars", "Ares", "Tyr", "Bael", "Zorn", "Drak", "Krev", "Hesh", "Roth"], "suffixes": ["thor", "gash", "gar", "ax", "rak", "us", "mor", "grim", "vash", "dun"] },
    "death":     { "prefixes": ["Mor", "Nec", "Sha", "Um", "Hel", "Osi", "Anu", "Ker", "Vael", "Grim", "Thal", "Ny"], "suffixes": ["thas", "bael", "oth", "is", "ys", "an", "mora", "reth", "wyn", "ux"] },
    "trade":     { "prefixes": ["Mer", "Aur", "Gil", "Herm", "Lak", "Chal", "Coen", "Vash", "Bral", "Orin"], "suffixes": ["ius", "ara", "os", "es", "us", "on", "eth", "andra", "or", "ian"] },
    "nature":    { "prefixes": ["Syl", "Fae", "Ver", "Oak", "Eld", "Gro", "Thal", "Wren", "Bri", "Lior"], "suffixes": ["nia", "an", "ia", "wyn", "oth", "el", "ara", "ith", "eth", "ora"] },
    "sky":       { "prefixes": ["Aer", "Thor", "Zeus", "Anu", "Shu", "Ven", "Sol", "Cael", "Wyn", "Astra"], "suffixes": ["us", "an", "os", "ar", "is", "iel", "eus", "ion", "wing", "reth"] },
    "sea":       { "prefixes": ["Pos", "Nep", "Ner", "Teth", "Oce", "Mar", "Thal", "Cor", "Aqua", "Riv"], "suffixes": ["idon", "tune", "eus", "ys", "an", "os", "ora", "wyn", "ia", "eth"] },
    "fire":      { "prefixes": ["Vol", "Pyr", "Agh", "Ifr", "Balt", "Surl", "Cind", "Ember", "Kael", "Drax"], "suffixes": ["can", "us", "ax", "oth", "os", "ur", "ash", "yre", "eth", "ion"] },
    "knowledge": { "prefixes": ["Ath", "Min", "Tho", "Ogs", "Wan", "Sap", "Loris", "Cael", "Vex", "Erud"], "suffixes": ["ena", "ot", "dius", "is", "ara", "iel", "eth", "wyn", "or", "ius"] }
  },
  "foreignPowerNouns": [
    "Reach", "Dominion", "Hold", "Throne", "Keep", "Realm", "Lands",
    "Kingdom", "Empire", "Horde", "Clan", "Dynasty", "Tribe", "Sovereignty",
    "Principality", "Confederation", "League", "Union", "March", "Expanse",
    "Alliance", "Assembly", "Bastion", "Coalition", "Collective", "Combine",
    "Commonwealth", "Compact", "Council", "Court", "Demesne", "Directorate",
    "Duchy", "Emirate", "Federation", "Fiefdom", "Frontier", "Hegemony",
    "Imperium", "Khanate", "Legion", "Marches", "Nation", "Order", "Outpost",
    "Pact", "Province", "Protectorate", "Regency", "Republic", "Sultanate",
    "Syndicate", "Territory", "Theocracy", "Vanguard", "Ward", "Wilds",
    "Suzerainty", "Domain", "Enclave"
  ],
  "guildAdjectives": [
    "Ancient", "Arcane", "Ashen", "Black", "Blind", "Blood",
    "Broken", "Burning", "Coin", "Crimson", "Crooked", "Cunning",
    "Dark", "Dawn", "Dusk", "Ember", "Exiled", "Fallen",
    "Free", "Ghost", "Gilded", "Golden", "Grey", "Grim",
    "Hidden", "Hollow", "Hungry", "Iron", "Ivory", "Jade",
    "Last", "Lost", "Marked", "Masked", "Merciless", "Midnight",
    "Obsidian", "Old", "Open", "Pale", "Quiet", "Red",
    "Rogue", "Rusted", "Sacred", "Scarlet", "Shadow", "Shattered",
    "Silent", "Silver", "Sinister", "Smoke", "Steel", "Storm",
    "Sunken", "Swift", "Thorn", "Twilight", "Undying", "Unveiled",
    "Veiled", "Void", "Wandering", "Wild", "Winding", "Withered",
    "Amber", "Azure", "Bitter", "Bleak", "Blighted", "Blue", "Bold", "Bone",
    "Brass", "Bright", "Bronze", "Brutal", "Burnished", "Chained", "Charred",
    "Cloaked", "Cobalt", "Copper", "Coral", "Crescent", "Crimsoned", "Crystal",
    "Damned", "Deathless", "Deep", "Defiant", "Deft", "Devout", "Diamond",
    "Discreet", "Doomed", "Dread", "Drifting", "Dying", "Eclipsed", "Elusive",
    "Emerald", "Endless", "Errant", "Faceless", "Faded", "Faithless", "Fatal",
    "Fearless", "Feral", "Fierce", "Flame", "Fleeting", "Forbidden", "Forsaken",
    "Frost", "Furtive", "Gaunt", "Ghastly", "Glass", "Gloaming", "Grave",
    "Green", "Grey-Eyed", "Guarded", "Harrowed", "Hawk", "Heretical", "Honed",
    "Howling", "Hushed", "Jagged", "Keen", "Knotted", "Lawless", "Lean",
    "Lingering", "Lithe", "Lucky", "Luminous", "Malicious", "Marrow",
    "Mercurial", "Mist", "Molten", "Moonless", "Mute", "Nameless", "Nightborn",
    "Nomad", "Onyx", "Opal", "Painted", "Perilous", "Phantom", "Piercing",
    "Poisoned", "Prowling", "Quicksilver", "Radiant", "Ravaged", "Reckless",
    "Relentless", "Restless", "Roaming", "Rooted", "Ruthless", "Sable", "Salt",
    "Savage", "Scorched", "Serpent", "Shifting", "Silvered", "Slate", "Sly",
    "Somber", "Sorrowful", "Spectral", "Splintered", "Steadfast", "Stealthy",
    "Stone", "Sunless", "Sworn", "Tainted", "Tangled", "Tarnished", "Tattered",
    "Thieving", "Thundering", "Umbral", "Unbroken", "Unforgiving", "Unseen",
    "Vengeful", "Vigilant", "Violet", "Vivid", "Wailing", "Wary", "Watchful",
    "Weeping", "Whispering", "White", "Wolfish", "Wounded", "Wrathful", "Wretched"
  ],
  "guildNouns": [
    "Accord", "Aegis", "Alliance", "Anvil", "Architects",
    "Assembly", "Banner", "Blade", "Blades", "Bond",
    "Brotherhood", "Circle", "Claw", "Claws", "Compact",
    "Company", "Conclave", "Consortium", "Covenant", "Crew",
    "Crown", "Dagger", "Dawn", "Eye", "Eyes", "Fang",
    "Fangs", "Fellowship", "Fist", "Fists", "Flame",
    "Forge", "Hand", "Hands", "Hook", "Hooks",
    "Host", "House", "Key", "Keys", "Knot", "League",
    "Lens", "Lodge", "Mantle", "Mark", "Mask", "Net",
    "Oath", "Order", "Pack", "Pact", "Path", "Ring",
    "Rose", "Scale", "Scales", "Seal", "Serpent", "Shadow",
    "Shadows", "Shield", "Sigil", "Society", "Spire", "Star",
    "Syndicate", "Thorn", "Thorns", "Thread", "Tome", "Tower",
    "Union", "Veil", "Voice", "Vow", "Watch", "Web", "Wing",
    "Archive", "Arrow", "Ashes", "Aspect", "Auger", "Aurora", "Axe", "Bastion",
    "Beacon", "Bell", "Bindings", "Blazon", "Blessing", "Bloom", "Bones",
    "Book", "Bower", "Bulwark", "Cabal", "Cauldron", "Chain", "Chains",
    "Chalice", "Chapter", "Charm", "Chord", "Circuit", "Citadel", "Clave",
    "Clock", "Cloister", "Coalition", "Coil", "Coils", "Collective", "Compass",
    "Confluence", "Congregation", "Conjuration", "Convocation", "Cord",
    "Coterie", "Council", "Court", "Craft", "Creed", "Crest", "Crook",
    "Crossing", "Crucible", "Crypt", "Current", "Cypher", "Diadem", "Dominion",
    "Dream", "Ember", "Embers", "Ensign", "Fable", "Fathom", "Feast", "Fetter",
    "Fold", "Font", "Fortune", "Foundry", "Fragment", "Frame", "Gate", "Gaze",
    "Ghost", "Gild", "Glade", "Glass", "Grail", "Grasp", "Grip", "Grove",
    "Guild", "Halo", "Harbor", "Harvest", "Haven", "Heart", "Hearth",
    "Heirloom", "Herald", "Hollow", "Horizon", "Horn", "Kindred", "Kinship",
    "Labyrinth", "Lantern", "Legacy", "Legion", "Lifeline", "Lineage", "Loom",
    "Loop", "Lore", "Lotus", "Loyalty", "Manifest", "Manor", "Maze", "Mirror",
    "Mosaic", "Nest", "Network", "Nexus", "Obelisk", "Pale", "Pallor",
    "Pattern", "Petal", "Phantom", "Pillar", "Pinion", "Ploy", "Plume",
    "Pool", "Portal", "Prophecy", "Pyre", "Quill", "Rampart", "Rank", "Reach",
    "Reckoning", "Relic", "Remnant", "Reprise", "Requiem", "Rift", "Rite",
    "Root", "Roots", "Rune", "Sanctuary", "Sanctum", "Scepter", "Scribe",
    "Scroll", "Seam", "Seer", "Sentinel", "Sept", "Shard", "Shears", "Shrine",
    "Skein", "Snare", "Sparrow", "Spear", "Spectre", "Sphere", "Spiral",
    "Spool", "Standard", "Stitch", "Summit", "Symbol", "Talon", "Talons",
    "Tapestry", "Temple", "Tendril", "Tether", "Throne", "Tide", "Torch",
    "Trace", "Trail", "Trellis", "Trust", "Tusk", "Umbrage", "Undertow",
    "Ward", "Warden", "Wardens", "Warrant", "Weal", "Weave", "Whisper",
    "Whisperers", "Wolves", "Wraith", "Wyrd", "Zephyr"
  ]
}

function _pick(arr) { return arr[Math.floor(Math.random() * arr.length)] }

// Generate one plausible name for the given district/terrain type and optional subType.
// districtType: 'Market' | 'Military' | 'Residential' | 'Entertainment' | 'Religious' |
//               'Magical' | 'Industry' | 'Leadership' | 'Slums' | 'Noble' | 'Monarchy' |
//               'Forestry' | 'Agriculture' | 'Mining' | 'Fishing' | etc.
export function generateName(districtType, subType) {
  const g = nameLibraryData.global
  const key = subType || districtType
  const pool = nameLibraryData.district[key] || nameLibraryData.district[districtType]
  const adjs  = pool?.adjectives || g.adjectives
  const nouns = pool?.nouns || g.districtSuffixes

  const pattern = Math.floor(Math.random() * 7)
  switch (pattern) {
    case 0: return `${_pick(adjs)} ${_pick(nouns)}`               // Gilded Hall
    case 1: return `${_pick(nouns)} of ${_pick(g.dramaticNouns)}` // Hall of Ruin
    case 2: return `${_pick(g.properNames)} ${_pick(nouns)}`       // Ulduar Court
    case 3: return `The ${_pick(adjs)} ${_pick(nouns)}`            // The Gilded Hall
    case 4: return `The ${_pick(nouns)}`                           // The Rookery
    case 5: return `${_pick(g.properNames)}`                       // Ulduar
    default: return `${_pick(nouns)}`                              // Rookery
  }
}

export default nameLibraryData
